from __future__ import annotations

_NICKNAME_MAP: dict[str, list[str]] = {
    "al": ["Albert", "Alan", "Alfred"],
    "albert": ["Al", "Bert"],
    "alan": ["Al"],
    "alex": ["Alexander", "Alexandra"],
    "alexander": ["Alex"],
    "alexandra": ["Alex", "Lexi"],
    "amy": ["Amelia", "Amanda"],
    "amelia": ["Amy"],
    "amanda": ["Mandy", "Amy"],
    "andy": ["Andrew", "Andrea"],
    "andrew": ["Andy", "Drew"],
    "andrea": ["Andy", "Andi"],
    "becky": ["Rebecca"],
    "ben": ["Benjamin"],
    "benjamin": ["Ben"],
    "beth": ["Elizabeth", "Bethany"],
    "bill": ["William"],
    "billy": ["William"],
    "bob": ["Robert"],
    "bobby": ["Robert"],
    "rob": ["Robert"],
    "robert": ["Bob", "Rob"],
    "charlie": ["Charles"],
    "charles": ["Charlie", "Chuck"],
    "chris": ["Christopher", "Christine", "Christina"],
    "christopher": ["Chris"],
    "christine": ["Chris", "Christy"],
    "chuck": ["Charles"],
    "dan": ["Daniel"],
    "daniel": ["Dan", "Danny"],
    "dave": ["David"],
    "david": ["Dave"],
    "debbie": ["Deborah"],
    "deborah": ["Debbie", "Deb"],
    "dick": ["Richard"],
    "don": ["Donald"],
    "donald": ["Don"],
    "doug": ["Douglas"],
    "douglas": ["Doug"],
    "drew": ["Andrew"],
    "ed": ["Edward", "Edwin"],
    "edward": ["Ed", "Ted"],
    "elizabeth": ["Liz", "Beth", "Lizzy"],
    "fred": ["Frederick"],
    "frederick": ["Fred", "Freddy"],
    "greg": ["Gregory"],
    "gregory": ["Greg"],
    "jack": ["John"],
    "jake": ["Jacob"],
    "jacob": ["Jake"],
    "james": ["Jim", "Jimmy"],
    "jeff": ["Jeffrey"],
    "jeffrey": ["Jeff"],
    "jen": ["Jennifer"],
    "jennifer": ["Jen", "Jenny"],
    "jerry": ["Jerome", "Gerald"],
    "jim": ["James"],
    "jimmy": ["James"],
    "joe": ["Joseph"],
    "joseph": ["Joe", "Joey"],
    "john": ["Jack", "Johnny"],
    "jon": ["Jonathan"],
    "jonathan": ["Jon", "John"],
    "kate": ["Katherine", "Kathryn"],
    "katherine": ["Kate", "Kathy"],
    "kathryn": ["Kate", "Kathy"],
    "kathy": ["Katherine", "Kathryn"],
    "ken": ["Kenneth"],
    "kenneth": ["Ken", "Kenny"],
    "larry": ["Lawrence", "Laurence"],
    "lawrence": ["Larry"],
    "liz": ["Elizabeth"],
    "mandy": ["Amanda"],
    "matt": ["Matthew"],
    "matthew": ["Matt"],
    "meg": ["Megan", "Margaret"],
    "megan": ["Meg"],
    "margaret": ["Meg", "Maggie", "Peggy"],
    "mike": ["Michael"],
    "michael": ["Mike"],
    "nick": ["Nicholas"],
    "nicholas": ["Nick"],
    "pat": ["Patrick", "Patricia"],
    "patrick": ["Pat"],
    "patricia": ["Pat", "Patty"],
    "pete": ["Peter"],
    "peter": ["Pete"],
    "phil": ["Philip"],
    "philip": ["Phil"],
    "ray": ["Raymond"],
    "raymond": ["Ray"],
    "rebecca": ["Becky"],
    "rich": ["Richard"],
    "richard": ["Rich", "Rick", "Dick"],
    "rick": ["Richard"],
    "ron": ["Ronald"],
    "ronald": ["Ron", "Ronnie"],
    "sam": ["Samuel", "Samantha"],
    "samuel": ["Sam"],
    "samantha": ["Sam"],
    "steve": ["Steven", "Stephen"],
    "steven": ["Steve"],
    "stephen": ["Steve"],
    "sue": ["Susan"],
    "susan": ["Sue", "Susie"],
    "ted": ["Edward", "Theodore"],
    "theodore": ["Ted", "Teddy"],
    "tom": ["Thomas"],
    "thomas": ["Tom", "Tommy"],
    "tony": ["Anthony"],
    "anthony": ["Tony"],
    "will": ["William"],
    "william": ["Will", "Bill", "Billy"],
}


def get_name_variants(first_name: str) -> list[str]:
    variants = [first_name]
    alts = _NICKNAME_MAP.get(first_name.lower(), [])
    variants.extend(alts[:2])
    return variants
